# -*- coding: utf-8 -*-
"""EU500_Exercício_Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qwoPVf15kVfL25G9aukmOUNDVBCi_enr
"""

import numpy as np

Matriz_A = np.zeros((12,12))
Vetor_B = np.zeros(12)

Vetor_B[0] = -1800
Vetor_B[2] = 2025
Vetor_B[3] = -900
Vetor_B[7] = -900

Matriz_A[0,0] = 1
Matriz_A[1,1] = 1
Matriz_A[1,2] = 1
Matriz_A[2,2] = 1
Matriz_A[3,3] = 1
Matriz_A[3,5] = 0.8
Matriz_A[4,4] = -1
Matriz_A[4,5] = -0.6
Matriz_A[5,3] = -1
Matriz_A[6,6] = -1
Matriz_A[7,7] = 1
Matriz_A[7,9] = 0.8
Matriz_A[0,0] = 1
Matriz_A[8,4] = -1
Matriz_A[8,8] = -1
Matriz_A[8,9] = -0.6
Matriz_A[9,5] = 0.8
Matriz_A[9,7] = 1
Matriz_A[10,5] = -0.6
Matriz_A[10,6] = -1
Matriz_A[10,10] = -1
Matriz_A[11,9] = 0.8
Matriz_A[11,11] = 1

print(Matriz_A)
print(Vetor_B)

F = np.linalg.solve(Matriz_A, Vetor_B)
#EX,EY,FY,F_AB,F_AC,F_AD,F_BD,F_CD,F_CE,F_CF,F_DF,F_EF
print(F)