# -*- coding: utf-8 -*-
"""EU500_FDM_transiente_beta_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f-dbMfRq81I4I4HtS2qpqR5y661R0QWh
"""

# beta = 1
# Modelo SIRD
import numpy as np
import matplotlib.pyplot as plt
import math

beta = 1;    # (novos infectados/infectados)/dt
gama = 0.05; # (recuperados/infectados)/dt
mi = 5e-4    # taxa de mortalidade
dt = 1       # 1 dia

m = 365; # periodos de simulação

# Cria vetores para armazenamento dos dados:
S = np.empty(m);
I = np.empty(m);
R = np.empty(m);
D = np.empty(m);
t = np.empty(m);

# Condições iniciais:
N = 209e6; # População brasileira
S[0] = N;
I[0] = 5; # Nùmero inicial de infectados
R[0] = 0; # Curados 
D[0] = 0; # Mortos
t[0] = 0; # tempo

for i in range(m-1):
  t[i+1] = t[i] + dt
  S[i+1] = S[i]*(1 - (beta*I[i]/N)*dt)
  I[i+1] = I[i]*(1 - dt*gama + (beta*S[i]/N)*dt - dt*mi)
  R[i+1] = R[i] + gama*I[i]*dt
  D[i+1] = D[i] + mi*I[i]*dt

texto = 'Número de mortos = '
texto2 = texto + str(math.floor(D[m-1]))

plt.plot(t,S,label='S')
plt.plot(t,I,label='I')
plt.plot(t,R,label='R')
plt.plot(t,D,label='D')
plt.annotate(texto2, (190,10000000))
plt.xlabel('tempo [dia]')
plt.ylabel('num. pessoas')
plt.legend()
plt.title('Beta = 1')
plt.savefig('FDM_transiente_beta_1.pdf')