# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12OzXvYtFcaWrQEKSVqVyUCeZkQbmUHP9
"""

import numpy as np;
from numpy import pi, cos, sin, sqrt, arctan2;

def Klocal(E,A,L):
    c1 = A * E / L;
    return np.array([[c1, 0, -c1, 0],
                     [0,0,0,0],
                     [-c1, 0, c1, 0],
                     [0,0,0,0]
                     ]);


def RotMat(alfa):
    return np.array([[cos(alfa), -sin(alfa), 0, 0],
                     [sin(alfa), cos(alfa), 0, 0],
                     [0, 0, cos(alfa), -sin(alfa)],
                     [0, 0, sin(alfa), cos(alfa)]]);


# Área da viga-barra (todas):
A = 25e-6;

# Módulo de elasticidade:
E = 70e9;

# Matriz de rigidez do sistema (ref. global) 3 nós x 3 g.d.l = 9:
Ksis = np.zeros((6,6));

# Cálculo da barra 1:
L1 = sqrt(0.5**2 + 0.5**2);
alfa1 = -pi/4;

K1local = Klocal(E,A,L1);
R1 = RotMat(alfa1);

K1global = R1.dot(K1local.dot(np.transpose(R1)));

# Montagem do K1global na matriz do sistema:
Ksis[2:4,2:4] += K1global[0:2,0:2]; # K22_barra1
Ksis[2:4,4:6] += K1global[0:2,2:4]; # K23_barra1
Ksis[4:6,2:4] += K1global[2:4,0:2]; # K32_barra1
Ksis[4:6,4:6] += K1global[2:4,2:4]; # K33_barra1

# Cálculo da barra 2:
L2 = 1;
alfa2 = 0;

K2local = Klocal(E,A,L2);
R2 = RotMat(alfa2);

K2global = R2.dot(K2local.dot(np.transpose(R2)));

# Montagem do K2global na matriz do sistema:
Ksis[0:2,0:2] += K2global[0:2,0:2]; # K11_barra2
Ksis[0:2,2:4] += K2global[0:2,2:4]; # K12_barra2
Ksis[2:4,0:2] += K2global[2:,0:2]; # K21_barra2
Ksis[2:4,2:4] += K2global[2:4,2:4]; # K22_barra2

# Cálculo da barra 3:
L3 = L1;
alfa3 = pi/4;

K3local = Klocal(E,A,L3);
R3 = RotMat(alfa3);

K3global = R3.dot(K3local.dot(np.transpose(R3)));

# Montagem do K3global na matriz do sistema:
Ksis[0:2,0:2] += K3global[0:2,0:2]; # K11_barra3
Ksis[0:2,4:6] += K3global[0:2,2:4]; # K13_barra3
Ksis[4:6,0:2] += K3global[2:4,0:2]; # K31_barra3
Ksis[4:6,4:6] += K3global[2:4,2:4]; # K33_barra3

# Redução da matriz para determinar somente deslocamento desconhecidos (x2, y2, x3)
Ksis_red = np.delete(Ksis, [0,1,5], 0); # exclui as linhas das forças desconhecidos
Ksis_red = np.delete(Ksis_red, [0,1,5], 1); # exclui as colunas dos deslocamentos conhecidos

# Vetor de forças reduzido
Fsis = np.array([0,-1000,0]); 

x = np.linalg.solve(Ksis_red, Fsis);

print("Deslocamentos (x2, y2, x3):\n",x)

# Cálculo das forças:
Ksis_red = np.delete(Ksis, [2,3,4], 0); # exclui as linhas dos deslocamentos desconhecidos
Ksis_red = np.delete(Ksis_red, [0,1,5], 1); # exclui as colunas dos deslocamentos conhecidos
f = Ksis_red.dot(x);

print("Forças (F1x, F1y, F3y):\n",f);

